#
# Generated by @zondax/cli
#
APP_NAME=golem

build:
	go mod tidy
	go generate
	go build -v -o output/$(APP_NAME)

run: build
	./output/$(APP_NAME) start

version: build
	./output/$(APP_NAME) version

clean:
	go clean

gitclean:
	git clean -xfd
	git submodule foreach --recursive git clean -xfd

install_lint:
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin latest

check-modtidy:
	go mod tidy
	git diff --exit-code -- go.mod go.sum

lint:
	golangci-lint --version
	golangci-lint run

earthly:
	earthly +all

docker-bash:
	docker run --platform linux/amd64 -it zondax/golem-dev:latest /bin/bash

docker-run:
	docker run --platform linux/amd64 -it zondax/golem-dev:latest

########################################

zondax-update:
	@npx -y @zondax/cli@latest update

# include if exists
-include Makefile.local.mk

.PHONY: *
