#
# Generated by @zondax/cli
#
APP_NAME=golem
PACKAGE_VERSION := github.com/zondax/golem

GIT_VERSION := $(shell git describe --tags --abbrev=0)
GIT_REVISION := $(shell git rev-parse --abbrev-ref HEAD)-$(shell git rev-parse --short HEAD)

ifeq ($(GIT_VERSION),)
GITVERSION := v0.0.0
endif

build:
	go build -ldflags "-X $(PACKAGE_VERSION).GitVersion=$(GIT_VERSION) -X $(PACKAGE_VERSION).GitRevision=$(GIT_REVISION)" -o $(APP_NAME)

run: build
	./$(APP_NAME) start

version: build
	./$(APP_NAME) version

clean:
	go clean

gitclean:
	git clean -xfd
	git submodule foreach --recursive git clean -xfd

install_lint:
	curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(shell go env GOPATH)/bin latest

check-modtidy:
	go mod tidy
	git diff --exit-code -- go.mod go.sum

lint:
	golangci-lint --version
	golangci-lint run

########################################

zdx-update:
	@npx -y @zondax/cli@latest update

# include if exists
-include Makefile.local.mk
