name: CI-go

on:
  push:
    branches: [main, master, dev]
  pull_request:
    branches: [main, master, dev]
  schedule:
    - cron: "0 0 * * *" # Every day at midnight UTC

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.head.ref }}
  cancel-in-progress: true

jobs:
  go-checks:
    uses: zondax/_workflows/.github/workflows/_checks-golang.yaml@main
    with:
      package_path: .
