// Code generated by mockery. DO NOT EDIT.

package zobservability

import mock "github.com/stretchr/testify/mock"

// MocktransactionOptionFunc is an autogenerated mock type for the transactionOptionFunc type
type MocktransactionOptionFunc struct {
	mock.Mock
}

type MocktransactionOptionFunc_Expecter struct {
	mock *mock.Mock
}

func (_m *MocktransactionOptionFunc) EXPECT() *MocktransactionOptionFunc_Expecter {
	return &MocktransactionOptionFunc_Expecter{mock: &_m.Mock}
}

// Execute provides a mock function with given fields: _a0
func (_m *MocktransactionOptionFunc) Execute(_a0 Transaction) {
	_m.Called(_a0)
}

// MocktransactionOptionFunc_Execute_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Execute'
type MocktransactionOptionFunc_Execute_Call struct {
	*mock.Call
}

// Execute is a helper method to define mock.On call
//   - _a0 Transaction
func (_e *MocktransactionOptionFunc_Expecter) Execute(_a0 interface{}) *MocktransactionOptionFunc_Execute_Call {
	return &MocktransactionOptionFunc_Execute_Call{Call: _e.mock.On("Execute", _a0)}
}

func (_c *MocktransactionOptionFunc_Execute_Call) Run(run func(_a0 Transaction)) *MocktransactionOptionFunc_Execute_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(Transaction))
	})
	return _c
}

func (_c *MocktransactionOptionFunc_Execute_Call) Return() *MocktransactionOptionFunc_Execute_Call {
	_c.Call.Return()
	return _c
}

func (_c *MocktransactionOptionFunc_Execute_Call) RunAndReturn(run func(Transaction)) *MocktransactionOptionFunc_Execute_Call {
	_c.Run(run)
	return _c
}

// NewMocktransactionOptionFunc creates a new instance of MocktransactionOptionFunc. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMocktransactionOptionFunc(t interface {
	mock.TestingT
	Cleanup(func())
}) *MocktransactionOptionFunc {
	mock := &MocktransactionOptionFunc{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
